<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="coverlet.collector" />
	  <PackageReference Include="Microsoft.NET.Test.Sdk" />
	  <PackageReference Include="xunit" />
	  <PackageReference Include="xunit.runner.visualstudio" />
	  <PackageReference Include="NetArchTest.Rules" />
  </ItemGroup>
  <ItemGroup>
	 <ProjectReference Include="..\..\src\Company.Product.Domain\Company.Product.Domain.csproj" />
	 <ProjectReference Include="..\..\src\Company.Product.Application\Company.Product.Application.csproj" />
	 <ProjectReference Include="..\..\src\Company.Product.Infrastructure\Company.Product.Infrastructure.csproj" />
	 <ProjectReference Include="..\..\src\Company.Product.Api\Company.Product.Api.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

</Project>
